GROQ_API_KEY = "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"      # preferred path
HF_TOKEN = "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"          # optional fallback
TOMORROW_API_KEY = "KL5eyVNrvwAiNpS4xWOBww4CpblJtTb4"   # optional if you use weather
