GROQ_API_KEY = "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"      # preferred path
HF_TOKEN = "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"         # optional fallback
TOMORROW_API_KEY = "KL5eyVNrvwAiNpS4xWOBww4CpblJtTb4"   # optional if you use weather
